keys_rf_to_prms = {
    "1 0 1 0": ["Discovered", "Reserves", "On production"],
    "2 0 1 0": ["Discovered", "Reserves", "Approved for Development"],
    "3 0 1 0": ["Discovered", "Reserves", "Justified for Development"],
    "1 0 2 0": ["Discovered", "Reserves", "On production"],
    "2 0 2 0": ["Discovered", "Reserves", "Approved for Development"],
    "3 0 2 0": ["Discovered", "Reserves", "Justified for Development"],
    "1 1 2 1": ["Discovered", "Contingent resources", "Development pending"],
    "2 1 2 1": ["Discovered", "Contingent resources", "Development pending"],
    "4 0 2 1": ["Discovered", "Contingent resources", "Development pending"],
    "3 1 2 1": ["Discovered", "Contingent resources", "Development pending"],
    "5 0 2 1": ["Discovered", "Contingent resources", "Development pending"],
    "1 1 2 2": ["Discovered", "Contingent resources", "Development pending"],
    "2 1 2 2": ["Discovered", "Contingent resources", "Development pending"],
    "3 1 2 2": ["Discovered", "Contingent resources", "Development pending"],
    "5 0 2 2": ["Discovered", "Contingent resources", "Development pending"],
    "4 0 2 2": ["Discovered", "Contingent resources", "Development pending"],
    "1 1 1 1": ["Discovered", "Contingent resources", "Development pending"],
    "2 1 1 1": ["Discovered", "Contingent resources", "Development pending"],
    "4 0 1 1": ["Discovered", "Contingent resources", "Development pending"],
    "3 1 1 1": ["Discovered", "Contingent resources", "Development pending"],
    "1 1 2 3": ["Discovered", "Contingent resources", "Development on hold"],
    "2 1 2 3": ["Discovered", "Contingent resources", "Development on hold"],
    "4 0 2 3": ["Discovered", "Contingent resources", "Development on hold"],
    "3 1 2 3": ["Discovered", "Contingent resources", "Development on hold"],
    "5 0 2 3": ["Discovered", "Contingent resources", "Development on hold"],
    "4 0 3 2": ["Discovered", "Contingent resources", "Development unclarified"],
    "5 0 3 2": ["Discovered", "Contingent resources", "Development unclarified"],
    "4 0 3 1": ["Discovered", "Contingent resources", "Development unclarified"],
    "5 0 3 1": ["Discovered", "Contingent resources", "Development unclarified"],
    "4 0 3 3": ["Discovered", "Contingent resources", "Development unclarified"],
    "5 0 3 3": ["Discovered", "Contingent resources", "Development unclarified"],
    "4 0 4 4": ["Discovered", "Contingent resources", "Development not viable"],
    "5 0 4 4": ["Discovered", "Contingent resources", "Development not viable"],
    "4 0 4 3": ["Discovered", "Contingent resources", "Development not viable"],
    "5 0 4 3": ["Discovered", "Contingent resources", "Development not viable"],
    "4 0 4 1": ["Discovered", "Contingent resources", "Development not viable"],
    "5 0 4 1": ["Discovered", "Contingent resources", "Development not viable"],
    "4 0 4 2": ["Discovered", "Contingent resources", "Development not viable"],
    "5 0 4 2": ["Discovered", "Contingent resources", "Development not viable"],
    "6 0 0 0": ["Undiscovered", "Prospective resources", "Prospect"],
    "7 0 0 0": ["Undiscovered", "Prospective resources", "Lead"],
    "8 0 0 0": ["Undiscovered", "Prospective resources", "Play"],
    "9 0 0 0": ["Undiscovered", "Prospective resources", "Play"],
    "1 2 0 0": ["--", "Unrecoverable", "--"],
    "2 2 0 0": ["--", "Unrecoverable", "--"],
    "3 2 0 0": ["--", "Unrecoverable", "--"],
    "4 2 0 0": ["--", "Unrecoverable", "--"],
    "5 2 0 0": ["--", "Unrecoverable", "--"],
    "6 2 0 0": ["--", "Unrecoverable", "--"],
    "7 2 0 0": ["--", "Unrecoverable", "--"],
    "8 2 0 0": ["--", "Unrecoverable", "--"],
    "9 2 0 0": ["--", "Unrecoverable", "--"],
}
