keys_rk_to_prms = {
    "1 1 1": ["Discovered", "Reserves", "On production"],
    "2 1 1": ["Discovered", "Reserves", "On production"],
    "1 2 1": ["Discovered", "Reserves", "Approved for development"],
    "2 2 1": ["Discovered", "Reserves", "Approved for development"],
    "1 3 1": ["Discovered", "Reserves", "Justified for development"],
    "2 3 1": ["Discovered", "Reserves", "Justified for development"],
    "1 4 1": ["Discovered", "Contingent resources", "Development pending"],
    "1 4 2": ["Discovered", "Contingent resources", "Development pending"],
    "3 1 1": ["Discovered", "Contingent resources", "Development pending"],
    "3 1 2": ["Discovered", "Contingent resources", "Development pending"],
    "3 2 1": ["Discovered", "Contingent resources", "Development pending"],
    "3 2 2": ["Discovered", "Contingent resources", "Development pending"],
    "3 3 1": ["Discovered", "Contingent resources", "Development on Hold"],
    "3 3 2": ["Discovered", "Contingent resources", "Development on Hold"],
    "4 1 1": ["Discovered", "Contingent resources", "Development unclarified"],
    "4 1 2": ["Discovered", "Contingent resources", "Development unclarified"],
    "4 2 1": ["Discovered", "Contingent resources", "Development unclarified"],
    "4 2 2": ["Discovered", "Contingent resources", "Development unclarified"],
    "4 3 1": ["Discovered", "Contingent resources", "Development unclarified"],
    "4 3 2": ["Discovered", "Contingent resources", "Development unclarified"],
    "5 1 1": ["Discovered", "Contingent resources", "Development not viable"],
    "5 1 2": ["Discovered", "Contingent resources", "Development not viable"],
    "5 2 1": ["Discovered", "Contingent resources", "Development not viable"],
    "5 2 2": ["Discovered", "Contingent resources", "Development not viable"],
    "5 3 1": ["Discovered", "Contingent resources", "Development not viable"],
    "5 3 2": ["Discovered", "Contingent resources", "Development not viable"],
    "5 4 1": ["Discovered", "Contingent resources", "Development not viable"],
    "5 4 2": ["Discovered", "Contingent resources", "Development not viable"],
    "4 4 1": ["Undiscovered", "Prospective resources", "Prospect"],
    "4 5 1": ["Undiscovered", "Prospective resources", "Lead"],
    "4 6 1": ["Undiscovered", "Prospective resources", "Play"],
    "5 5 1": ["Discovered", "Unrecoverable", "--"],
    "5 5 2": ["Discovered", "Unrecoverable", "--"],
    "5 5 3": ["Undiscovered", "Unrecoverable", "--"],
}