# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pr_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1028, 542)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1028, 542))
        MainWindow.setMaximumSize(QtCore.QSize(1028, 542))
        MainWindow.setBaseSize(QtCore.QSize(1028, 542))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #F0F1EB;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(24, 20, 476, 445))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"    padding-top: 4px;\n"
"    padding-bottom: 4px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    width: 157;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    border-top: 2px solid #C2C7CB;\n"
"    alignment: center;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: #F0F1EB\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"  \n"
"    background: #ffffff;\n"
"}\n"
"QTabWidget::pane{}\n"
"QTabBar::tab.rf2013{\n"
"    border-top-left-radius: 30px;\n"
"}\n"
"QTabWidget::tab-bar{\n"
"border-top-left-radius: 30px;\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.rf2013 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.rf2013.setFont(font)
        self.rf2013.setStyleSheet("QTabWidget::pane {}")
        self.rf2013.setObjectName("rf2013")
        self.frame = QtWidgets.QFrame(self.rf2013)
        self.frame.setGeometry(QtCore.QRect(-4, 4, 477, 397))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("Background-color: #ffffff;\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(92, 72, 109, 49))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.in_rf_category = QtWidgets.QComboBox(self.groupBox)
        self.in_rf_category.setEnabled(True)
        self.in_rf_category.setGeometry(QtCore.QRect(4, 16, 99, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.in_rf_category.setFont(font)
        self.in_rf_category.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_rf_category.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rf_category.setEditable(False)
        self.in_rf_category.setFrame(True)
        self.in_rf_category.setObjectName("in_rf_category")
        self.in_rf_category.addItem("")
        self.in_rf_category.setItemText(0, "")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(92, 160, 249, 49))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.in_rf_que_1 = QtWidgets.QComboBox(self.groupBox_2)
        self.in_rf_que_1.setGeometry(QtCore.QRect(4, 16, 241, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        self.in_rf_que_1.setFont(font)
        self.in_rf_que_1.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_rf_que_1.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rf_que_1.setEditable(False)
        self.in_rf_que_1.setObjectName("in_rf_que_1")
        self.in_rf_que_1.addItem("")
        self.in_rf_que_1.setItemText(0, "")
        self.in_rf_que_1.addItem("")
        self.in_rf_que_1.addItem("")
        self.in_rf_que_1.addItem("")
        self.in_rf_que_1.addItem("")
        self.in_rf_que_1.addItem("")
        self.in_rf_que_1.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setGeometry(QtCore.QRect(92, 232, 249, 49))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.in_rf_que_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.in_rf_que_2.setGeometry(QtCore.QRect(4, 16, 241, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.in_rf_que_2.setFont(font)
        self.in_rf_que_2.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_rf_que_2.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rf_que_2.setEditable(False)
        self.in_rf_que_2.setObjectName("in_rf_que_2")
        self.in_rf_que_2.addItem("")
        self.in_rf_que_2.setItemText(0, "")
        self.in_rf_que_2.addItem("")
        self.in_rf_que_2.addItem("")
        self.in_rf_que_2.addItem("")
        self.in_rf_que_2.addItem("")
        self.in_rf_que_2.addItem("")
        self.in_rf_que_2.addItem("")
        self.in_rf_stars = QtWidgets.QTabWidget(self.frame)
        self.in_rf_stars.setEnabled(True)
        self.in_rf_stars.setGeometry(QtCore.QRect(240, 84, 197, 33))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        self.in_rf_stars.setFont(font)
        self.in_rf_stars.setStyleSheet("QTabBar::tab {\n"
"    border: 2px solid #C4C4C3;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"    width: 40;\n"
"    margin: 2;\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected {\n"
"    border: 2px solid gray;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}")
        self.in_rf_stars.setObjectName("in_rf_stars")
        self.in_rf_stars_nonetab = QtWidgets.QWidget()
        self.in_rf_stars_nonetab.setObjectName("in_rf_stars_nonetab")
        self.in_rf_stars.addTab(self.in_rf_stars_nonetab, "")
        self.in_rf_stars_onetab = QtWidgets.QWidget()
        self.in_rf_stars_onetab.setObjectName("in_rf_stars_onetab")
        self.in_rf_stars.addTab(self.in_rf_stars_onetab, "")
        self.in_rf_stars_twotab = QtWidgets.QWidget()
        self.in_rf_stars_twotab.setObjectName("in_rf_stars_twotab")
        self.in_rf_stars.addTab(self.in_rf_stars_twotab, "")
        self.tabWidget.addTab(self.rf2013, "РФ-2013")
        self.rkoon = QtWidgets.QWidget()
        self.rkoon.setStyleSheet("")
        self.rkoon.setObjectName("rkoon")
        self.frame_2 = QtWidgets.QFrame(self.rkoon)
        self.frame_2.setGeometry(QtCore.QRect(-1, 4, 473, 397))
        self.frame_2.setStyleSheet("Background-color: #ffffff;\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_4.setGeometry(QtCore.QRect(80, 88, 69, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.in_rk_e = QtWidgets.QComboBox(self.groupBox_4)
        self.in_rk_e.setEnabled(True)
        self.in_rk_e.setGeometry(QtCore.QRect(4, 12, 61, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.in_rk_e.setFont(font)
        self.in_rk_e.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down {width:1}\n"
"")
        self.in_rk_e.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rk_e.setEditable(False)
        self.in_rk_e.setIconSize(QtCore.QSize(16, 16))
        self.in_rk_e.setFrame(True)
        self.in_rk_e.setObjectName("in_rk_e")
        self.in_rk_e.addItem("")
        self.in_rk_e.addItem("")
        self.in_rk_e.addItem("")
        self.in_rk_e.addItem("")
        self.in_rk_e.addItem("")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setGeometry(QtCore.QRect(196, 88, 69, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.in_rk_f = QtWidgets.QComboBox(self.groupBox_5)
        self.in_rk_f.setEnabled(True)
        self.in_rk_f.setGeometry(QtCore.QRect(4, 12, 61, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.in_rk_f.setFont(font)
        self.in_rk_f.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down {width:1}\n"
"")
        self.in_rk_f.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rk_f.setEditable(False)
        self.in_rk_f.setIconSize(QtCore.QSize(16, 16))
        self.in_rk_f.setFrame(True)
        self.in_rk_f.setObjectName("in_rk_f")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_6.setGeometry(QtCore.QRect(320, 88, 69, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_6.setObjectName("groupBox_6")
        self.in_rk_g = QtWidgets.QComboBox(self.groupBox_6)
        self.in_rk_g.setEnabled(True)
        self.in_rk_g.setGeometry(QtCore.QRect(4, 12, 61, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.in_rk_g.setFont(font)
        self.in_rk_g.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down {width:1}\n"
"")
        self.in_rk_g.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rk_g.setEditable(False)
        self.in_rk_g.setIconSize(QtCore.QSize(16, 16))
        self.in_rk_g.setFrame(True)
        self.in_rk_g.setObjectName("in_rk_g")
        self.in_rk_g.addItem("")
        self.in_rk_g.addItem("")
        self.in_rk_g.addItem("")
        self.in_rk_g.addItem("")
        self.in_rk_g.addItem("")
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_7.setGeometry(QtCore.QRect(124, 152, 249, 49))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_7.setObjectName("groupBox_7")
        self.in_rk_que_1 = QtWidgets.QComboBox(self.groupBox_7)
        self.in_rk_que_1.setGeometry(QtCore.QRect(4, 16, 241, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        self.in_rk_que_1.setFont(font)
        self.in_rk_que_1.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_rk_que_1.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rk_que_1.setEditable(False)
        self.in_rk_que_1.setObjectName("in_rk_que_1")
        self.in_rk_que_1.addItem("")
        self.in_rk_que_1.setItemText(0, "")
        self.in_rk_que_1.addItem("")
        self.in_rk_que_1.addItem("")
        self.in_rk_que_1.addItem("")
        self.in_rk_que_1.addItem("")
        self.in_rk_que_1.addItem("")
        self.in_rk_que_1.addItem("")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_8.setGeometry(QtCore.QRect(128, 240, 249, 49))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_8.setObjectName("groupBox_8")
        self.in_rk_que_2 = QtWidgets.QComboBox(self.groupBox_8)
        self.in_rk_que_2.setGeometry(QtCore.QRect(4, 16, 241, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        self.in_rk_que_2.setFont(font)
        self.in_rk_que_2.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_rk_que_2.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rk_que_2.setEditable(False)
        self.in_rk_que_2.setObjectName("in_rk_que_2")
        self.in_rk_que_2.addItem("")
        self.in_rk_que_2.setItemText(0, "")
        self.in_rk_que_2.addItem("")
        self.in_rk_que_2.addItem("")
        self.in_rk_que_2.addItem("")
        self.in_rk_que_2.addItem("")
        self.in_rk_que_2.addItem("")
        self.in_rk_que_2.addItem("")
        self.tabWidget.addTab(self.rkoon, "")
        self.prms = QtWidgets.QWidget()
        self.prms.setObjectName("prms")
        self.frame_3 = QtWidgets.QFrame(self.prms)
        self.frame_3.setGeometry(QtCore.QRect(0, 4, 473, 397))
        self.frame_3.setStyleSheet("Background-color: #ffffff;\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_9.setGeometry(QtCore.QRect(92, 52, 249, 49))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_9.setObjectName("groupBox_9")
        self.in_prms_subclass = QtWidgets.QComboBox(self.groupBox_9)
        self.in_prms_subclass.setGeometry(QtCore.QRect(4, 16, 241, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        self.in_prms_subclass.setFont(font)
        self.in_prms_subclass.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_prms_subclass.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_prms_subclass.setEditable(False)
        self.in_prms_subclass.setObjectName("in_prms_subclass")
        self.in_prms_subclass.addItem("")
        self.in_prms_subclass.setItemText(0, "")
        self.in_prms_subclass.addItem("")
        self.in_prms_subclass.addItem("")
        self.in_prms_subclass.addItem("")
        self.in_prms_subclass.addItem("")
        self.in_prms_subclass.addItem("")
        self.in_prms_subclass.addItem("")
        self.groupBox_10 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_10.setGeometry(QtCore.QRect(88, 128, 249, 49))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_10.setObjectName("groupBox_10")
        self.in_prms_profit = QtWidgets.QComboBox(self.groupBox_10)
        self.in_prms_profit.setGeometry(QtCore.QRect(4, 24, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        self.in_prms_profit.setFont(font)
        self.in_prms_profit.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_prms_profit.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_prms_profit.setEditable(False)
        self.in_prms_profit.setObjectName("in_prms_profit")
        self.in_prms_profit.addItem("")
        self.in_prms_profit.setItemText(0, "")
        self.in_prms_profit.addItem("")
        self.in_prms_profit.addItem("")
        self.in_prms_profit.addItem("")
        self.in_prms_profit.addItem("")
        self.in_prms_profit.addItem("")
        self.in_prms_profit.addItem("")
        self.groupBox_11 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_11.setGeometry(QtCore.QRect(84, 208, 249, 53))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_11.setObjectName("groupBox_11")
        self.in_prms_subclass_2 = QtWidgets.QComboBox(self.groupBox_11)
        self.in_prms_subclass_2.setGeometry(QtCore.QRect(4, 24, 241, 25))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        self.in_prms_subclass_2.setFont(font)
        self.in_prms_subclass_2.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_prms_subclass_2.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_prms_subclass_2.setEditable(False)
        self.in_prms_subclass_2.setObjectName("in_prms_subclass_2")
        self.in_prms_subclass_2.addItem("")
        self.in_prms_subclass_2.setItemText(0, "")
        self.in_prms_subclass_2.addItem("")
        self.in_prms_subclass_2.addItem("")
        self.in_prms_subclass_2.addItem("")
        self.in_prms_subclass_2.addItem("")
        self.in_prms_subclass_2.addItem("")
        self.in_prms_subclass_2.addItem("")
        self.tabWidget.addTab(self.prms, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(524, 20, 476, 456))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setStyleSheet("QTabBar::tab {\n"
"    padding-top: 4px;\n"
"    padding-bottom: 4px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    width: 157;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    border-top: 2px solid #C2C7CB;\n"
"    alignment: center;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: #F0F1EB\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"  \n"
"    background: #ffffff;\n"
"}\n"
"QTabWidget::pane{}\n"
"QTabBar::tab.rf2013{\n"
"    border-top-left-radius: 30px;\n"
"}\n"
"QTabWidget::tab-bar{\n"
"border-top-left-radius: 30px;\n"
"}")
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.rf2013_2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.rf2013_2.setFont(font)
        self.rf2013_2.setStyleSheet("QTabWidget::pane {}")
        self.rf2013_2.setObjectName("rf2013_2")
        self.frame_4 = QtWidgets.QFrame(self.rf2013_2)
        self.frame_4.setGeometry(QtCore.QRect(-4, 4, 477, 397))
        self.frame_4.setStyleSheet("Background-color: #ffffff;\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(44, 116, 389, 129))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.out_rf_category = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rf_category.setFont(font)
        self.out_rf_category.setObjectName("out_rf_category")
        self.horizontalLayout_10.addWidget(self.out_rf_category)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.out_rf_profit = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rf_profit.setFont(font)
        self.out_rf_profit.setObjectName("out_rf_profit")
        self.horizontalLayout_9.addWidget(self.out_rf_profit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.tabWidget_2.addTab(self.rf2013_2, "РФ-2013")
        self.rkoon_2 = QtWidgets.QWidget()
        self.rkoon_2.setStyleSheet("")
        self.rkoon_2.setObjectName("rkoon_2")
        self.frame_5 = QtWidgets.QFrame(self.rkoon_2)
        self.frame_5.setGeometry(QtCore.QRect(0, 4, 473, 397))
        self.frame_5.setStyleSheet("Background-color: #ffffff;\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(44, 12, 403, 365))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.out_rk_superclass = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_superclass.setFont(font)
        self.out_rk_superclass.setObjectName("out_rk_superclass")
        self.horizontalLayout_3.addWidget(self.out_rk_superclass)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.out_rk_class = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_class.setFont(font)
        self.out_rk_class.setObjectName("out_rk_class")
        self.horizontalLayout_6.addWidget(self.out_rk_class)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.out_rk_subclass = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_subclass.setFont(font)
        self.out_rk_subclass.setObjectName("out_rk_subclass")
        self.horizontalLayout_7.addWidget(self.out_rk_subclass)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setStyleSheet("background-color: #F0F1EB;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.out_rk_e_num = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_e_num.setFont(font)
        self.out_rk_e_num.setObjectName("out_rk_e_num")
        self.horizontalLayout_8.addWidget(self.out_rk_e_num)
        self.out_rk_e_lett = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_e_lett.setFont(font)
        self.out_rk_e_lett.setObjectName("out_rk_e_lett")
        self.horizontalLayout_8.addWidget(self.out_rk_e_lett)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_8.setStretch(2, 6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.out_rk_f_num = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_f_num.setFont(font)
        self.out_rk_f_num.setObjectName("out_rk_f_num")
        self.horizontalLayout_4.addWidget(self.out_rk_f_num)
        self.out_rk_g_lett_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_g_lett_2.setFont(font)
        self.out_rk_g_lett_2.setObjectName("out_rk_g_lett_2")
        self.horizontalLayout_4.addWidget(self.out_rk_g_lett_2)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.out_rk_g_num = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_g_num.setFont(font)
        self.out_rk_g_num.setObjectName("out_rk_g_num")
        self.horizontalLayout_5.addWidget(self.out_rk_g_num)
        self.out_rk_g_lett = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_g_lett.setFont(font)
        self.out_rk_g_lett.setObjectName("out_rk_g_lett")
        self.horizontalLayout_5.addWidget(self.out_rk_g_lett)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tabWidget_2.addTab(self.rkoon_2, "")
        self.prms_2 = QtWidgets.QWidget()
        self.prms_2.setObjectName("prms_2")
        self.frame_6 = QtWidgets.QFrame(self.prms_2)
        self.frame_6.setGeometry(QtCore.QRect(-4, 4, 477, 397))
        self.frame_6.setStyleSheet("Background-color: #ffffff;\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_6)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(44, 92, 401, 189))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.out_prms_superclass = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_prms_superclass.setFont(font)
        self.out_prms_superclass.setObjectName("out_prms_superclass")
        self.horizontalLayout_11.addWidget(self.out_prms_superclass)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        self.out_prms_class = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_prms_class.setFont(font)
        self.out_prms_class.setObjectName("out_prms_class")
        self.horizontalLayout_12.addWidget(self.out_prms_class)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        self.out_prms_subclass = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_prms_subclass.setFont(font)
        self.out_prms_subclass.setObjectName("out_prms_subclass")
        self.horizontalLayout_13.addWidget(self.out_prms_subclass)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.tabWidget_2.addTab(self.prms_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.in_rf_stars.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "/"))
        self.in_rf_category.setItemText(1, _translate("MainWindow", "A"))
        self.in_rf_category.setItemText(2, _translate("MainWindow", "B1"))
        self.in_rf_category.setItemText(3, _translate("MainWindow", "B2"))
        self.in_rf_category.setItemText(4, _translate("MainWindow", "C1"))
        self.in_rf_category.setItemText(5, _translate("MainWindow", "C2"))
        self.in_rf_category.setItemText(6, _translate("MainWindow", "D0"))
        self.in_rf_category.setItemText(7, _translate("MainWindow", "Dл"))
        self.in_rf_category.setItemText(8, _translate("MainWindow", "D1"))
        self.in_rf_category.setItemText(9, _translate("MainWindow", "D2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Экономическая рентабельность"))
        self.in_rf_que_1.setItemText(1, _translate("MainWindow", "Нет уточнений"))
        self.in_rf_que_1.setItemText(2, _translate("MainWindow", "Рентабельны"))
        self.in_rf_que_1.setItemText(3, _translate("MainWindow", "Рентабельны в перспективе"))
        self.in_rf_que_1.setItemText(4, _translate("MainWindow", "Рентабельность не известна"))
        self.in_rf_que_1.setItemText(5, _translate("MainWindow", "Не рентабельны"))
        self.in_rf_que_1.setItemText(6, _translate("MainWindow", "Добываются в убыток"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Стадия освоения"))
        self.in_rf_que_2.setItemText(1, _translate("MainWindow", "Нет уточнений"))
        self.in_rf_que_2.setItemText(2, _translate("MainWindow", "Рентабельны"))
        self.in_rf_que_2.setItemText(3, _translate("MainWindow", "Рентабельны в перспективе"))
        self.in_rf_que_2.setItemText(4, _translate("MainWindow", "Рентабельность не известна"))
        self.in_rf_que_2.setItemText(5, _translate("MainWindow", "Не рентабельны"))
        self.in_rf_que_2.setItemText(6, _translate("MainWindow", "Добываются в убыток"))
        self.in_rf_stars.setTabText(self.in_rf_stars.indexOf(self.in_rf_stars_nonetab), _translate("MainWindow", "none"))
        self.in_rf_stars.setTabText(self.in_rf_stars.indexOf(self.in_rf_stars_onetab), _translate("MainWindow", "*"))
        self.in_rf_stars.setTabText(self.in_rf_stars.indexOf(self.in_rf_stars_twotab), _translate("MainWindow", "**"))
        self.groupBox_4.setTitle(_translate("MainWindow", "E"))
        self.in_rk_e.setItemText(0, _translate("MainWindow", "1"))
        self.in_rk_e.setItemText(1, _translate("MainWindow", "2"))
        self.in_rk_e.setItemText(2, _translate("MainWindow", "112"))
        self.in_rk_e.setItemText(3, _translate("MainWindow", "3"))
        self.in_rk_e.setItemText(4, _translate("MainWindow", "33"))
        self.groupBox_5.setTitle(_translate("MainWindow", "F"))
        self.in_rk_f.setItemText(0, _translate("MainWindow", "1"))
        self.in_rk_f.setItemText(1, _translate("MainWindow", "2"))
        self.in_rk_f.setItemText(2, _translate("MainWindow", "112"))
        self.in_rk_f.setItemText(3, _translate("MainWindow", "3"))
        self.in_rk_f.setItemText(4, _translate("MainWindow", "33"))
        self.groupBox_6.setTitle(_translate("MainWindow", "G"))
        self.in_rk_g.setItemText(0, _translate("MainWindow", "1"))
        self.in_rk_g.setItemText(1, _translate("MainWindow", "2"))
        self.in_rk_g.setItemText(2, _translate("MainWindow", "112"))
        self.in_rk_g.setItemText(3, _translate("MainWindow", "3"))
        self.in_rk_g.setItemText(4, _translate("MainWindow", "33"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Экономическая рентабельность"))
        self.in_rk_que_1.setItemText(1, _translate("MainWindow", "Нет уточнений"))
        self.in_rk_que_1.setItemText(2, _translate("MainWindow", "Рентабельны"))
        self.in_rk_que_1.setItemText(3, _translate("MainWindow", "Рентабельны в перспективе"))
        self.in_rk_que_1.setItemText(4, _translate("MainWindow", "Рентабельность не известна"))
        self.in_rk_que_1.setItemText(5, _translate("MainWindow", "Не рентабельны"))
        self.in_rk_que_1.setItemText(6, _translate("MainWindow", "Добываются в убыток"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Степень разведанности"))
        self.in_rk_que_2.setItemText(1, _translate("MainWindow", "Нет уточнений"))
        self.in_rk_que_2.setItemText(2, _translate("MainWindow", "Рентабельны"))
        self.in_rk_que_2.setItemText(3, _translate("MainWindow", "Рентабельны в перспективе"))
        self.in_rk_que_2.setItemText(4, _translate("MainWindow", "Рентабельность не известна"))
        self.in_rk_que_2.setItemText(5, _translate("MainWindow", "Не рентабельны"))
        self.in_rk_que_2.setItemText(6, _translate("MainWindow", "Добываются в убыток"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rkoon), _translate("MainWindow", "РКООН"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Подкласс"))
        self.in_prms_subclass.setItemText(1, _translate("MainWindow", "Нет уточнений"))
        self.in_prms_subclass.setItemText(2, _translate("MainWindow", "Рентабельны"))
        self.in_prms_subclass.setItemText(3, _translate("MainWindow", "Рентабельны в перспективе"))
        self.in_prms_subclass.setItemText(4, _translate("MainWindow", "Рентабельность не известна"))
        self.in_prms_subclass.setItemText(5, _translate("MainWindow", "Не рентабельны"))
        self.in_prms_subclass.setItemText(6, _translate("MainWindow", "Добываются в убыток"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Экономическая рентабельность"))
        self.in_prms_profit.setItemText(1, _translate("MainWindow", "Нет уточнений"))
        self.in_prms_profit.setItemText(2, _translate("MainWindow", "Рентабельны"))
        self.in_prms_profit.setItemText(3, _translate("MainWindow", "Рентабельны в перспективе"))
        self.in_prms_profit.setItemText(4, _translate("MainWindow", "Рентабельность не известна"))
        self.in_prms_profit.setItemText(5, _translate("MainWindow", "Не рентабельны"))
        self.in_prms_profit.setItemText(6, _translate("MainWindow", "Добываются в убыток"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Степень освоения"))
        self.in_prms_subclass_2.setItemText(1, _translate("MainWindow", "Нет уточнений"))
        self.in_prms_subclass_2.setItemText(2, _translate("MainWindow", "Рентабельны"))
        self.in_prms_subclass_2.setItemText(3, _translate("MainWindow", "Рентабельны в перспективе"))
        self.in_prms_subclass_2.setItemText(4, _translate("MainWindow", "Рентабельность не известна"))
        self.in_prms_subclass_2.setItemText(5, _translate("MainWindow", "Не рентабельны"))
        self.in_prms_subclass_2.setItemText(6, _translate("MainWindow", "Добываются в убыток"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.prms), _translate("MainWindow", "PRMS"))
        self.label_18.setText(_translate("MainWindow", "Категория:"))
        self.out_rf_category.setText(_translate("MainWindow", "Текст"))
        self.label_17.setText(_translate("MainWindow", "Рентабельность:"))
        self.out_rf_profit.setText(_translate("MainWindow", "Текст"))
        self.label.setText(_translate("MainWindow", "Надкласс"))
        self.out_rk_superclass.setText(_translate("MainWindow", "Известные источники"))
        self.label_8.setText(_translate("MainWindow", "Класс"))
        self.out_rk_class.setText(_translate("MainWindow", "Промышленные проекты"))
        self.label_3.setText(_translate("MainWindow", "Подкласс"))
        self.out_rk_subclass.setText(_translate("MainWindow", "В разработке"))
        self.label_5.setText(_translate("MainWindow", "Ось E"))
        self.out_rk_e_num.setText(_translate("MainWindow", "2.3"))
        self.out_rk_e_lett.setText(_translate("MainWindow", "Разработка не планируется"))
        self.label_4.setText(_translate("MainWindow", "Ось F"))
        self.out_rk_f_num.setText(_translate("MainWindow", "1.1"))
        self.out_rk_g_lett_2.setText(_translate("MainWindow", "Рентабельна"))
        self.label_6.setText(_translate("MainWindow", "Ось G"))
        self.out_rk_g_num.setText(_translate("MainWindow", "1"))
        self.out_rk_g_lett.setText(_translate("MainWindow", "Высоко достоверны"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.rkoon_2), _translate("MainWindow", "РКООН"))
        self.label_21.setText(_translate("MainWindow", "Надкласс:"))
        self.out_prms_superclass.setText(_translate("MainWindow", "Текст"))
        self.label_23.setText(_translate("MainWindow", "Класс:"))
        self.out_prms_class.setText(_translate("MainWindow", "Текст"))
        self.label_25.setText(_translate("MainWindow", "Подкласс:"))
        self.out_prms_subclass.setText(_translate("MainWindow", "Текст"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.prms_2), _translate("MainWindow", "PRMS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
