# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pr_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(QtCore.QSize(908, 465))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #F0F1EB;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget.setSizePolicy(sizePolicy)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.in_categories = QtWidgets.QTabWidget(self.centralwidget)
        self.in_categories.setGeometry(QtCore.QRect(28, 32, 412, 412))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_categories.sizePolicy().hasHeightForWidth())
        self.in_categories.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        self.in_categories.setFont(font)
        self.in_categories.setAutoFillBackground(False)
        self.in_categories.setStyleSheet("QTabBar::tab {\n"
"    padding-top: 4px;\n"
"    padding-bottom: 4px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    width: 205;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    border-top: 2px solid #C2C7CB;\n"
"    alignment: center;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: #F0F1EB\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background: #ffffff;\n"
"}\n"
"\n"
"QTabWidget::pane{}\n"
"QTabBar::tab.rf2013{\n"
"    border-top-left-radius: 30px;\n"
"}\n"
"QTabWidget::tab-bar{\n"
"border-top-left-radius: 30px;\n"
"}")
        self.in_categories.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.in_categories.setObjectName("in_categories")
        self.rf_in = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.rf_in.setFont(font)
        self.rf_in.setStyleSheet("QTabWidget::pane {}")
        self.rf_in.setObjectName("rf_in")
        self.frame = QtWidgets.QFrame(self.rf_in)
        self.frame.setGeometry(QtCore.QRect(0, 4, 412, 364))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("Background-color: #ffffff;\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(43, 51, 125, 57))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.in_rf_category = QtWidgets.QComboBox(self.groupBox)
        self.in_rf_category.setEnabled(True)
        self.in_rf_category.setGeometry(QtCore.QRect(4, 16, 117, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_rf_category.sizePolicy().hasHeightForWidth())
        self.in_rf_category.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.in_rf_category.setFont(font)
        self.in_rf_category.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_rf_category.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rf_category.setEditable(False)
        self.in_rf_category.setFrame(True)
        self.in_rf_category.setObjectName("in_rf_category")
        self.in_rf_category.addItem("")
        self.in_rf_category.setItemText(0, "")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_category.addItem("")
        self.in_rf_stars = QtWidgets.QTabWidget(self.frame)
        self.in_rf_stars.setEnabled(True)
        self.in_rf_stars.setGeometry(QtCore.QRect(215, 70, 159, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_rf_stars.sizePolicy().hasHeightForWidth())
        self.in_rf_stars.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        self.in_rf_stars.setFont(font)
        self.in_rf_stars.setStyleSheet("QTabBar::tab {\n"
"    border: 2px solid #C4C4C3;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"    width: 40;\n"
"    margin: 2;\n"
"}\n"
"\n"
"\n"
"\n"
"QTabBar::tab:selected {\n"
"    border: 2px solid gray;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}")
        self.in_rf_stars.setObjectName("in_rf_stars")
        self.in_rf_stars_nonetab = QtWidgets.QWidget()
        self.in_rf_stars_nonetab.setObjectName("in_rf_stars_nonetab")
        self.in_rf_stars.addTab(self.in_rf_stars_nonetab, "")
        self.in_rf_stars_onetab = QtWidgets.QWidget()
        self.in_rf_stars_onetab.setObjectName("in_rf_stars_onetab")
        self.in_rf_stars.addTab(self.in_rf_stars_onetab, "")
        self.in_rf_stars_twotab = QtWidgets.QWidget()
        self.in_rf_stars_twotab.setObjectName("in_rf_stars_twotab")
        self.in_rf_stars.addTab(self.in_rf_stars_twotab, "")
        self.in_rf_que_2_box = QtWidgets.QGroupBox(self.frame)
        self.in_rf_que_2_box.setGeometry(QtCore.QRect(76, 251, 249, 69))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_rf_que_2_box.sizePolicy().hasHeightForWidth())
        self.in_rf_que_2_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.in_rf_que_2_box.setFont(font)
        self.in_rf_que_2_box.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px\n"
"}")
        self.in_rf_que_2_box.setObjectName("in_rf_que_2_box")
        self.in_rf_que_2 = QtWidgets.QComboBox(self.in_rf_que_2_box)
        self.in_rf_que_2.setGeometry(QtCore.QRect(4, 16, 241, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_rf_que_2.sizePolicy().hasHeightForWidth())
        self.in_rf_que_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.in_rf_que_2.setFont(font)
        self.in_rf_que_2.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_rf_que_2.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rf_que_2.setEditable(False)
        self.in_rf_que_2.setObjectName("in_rf_que_2")
        self.in_rf_que_2.addItem("")
        self.in_rf_que_2.setItemText(0, "")
        self.in_rf_que_2.addItem("")
        self.in_rf_que_2.addItem("")
        self.in_rf_que_2.addItem("")
        self.in_rf_que_2.addItem("")
        self.in_rf_que_1_box = QtWidgets.QGroupBox(self.frame)
        self.in_rf_que_1_box.setGeometry(QtCore.QRect(76, 148, 249, 69))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_rf_que_1_box.sizePolicy().hasHeightForWidth())
        self.in_rf_que_1_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.in_rf_que_1_box.setFont(font)
        self.in_rf_que_1_box.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"\n"
"}")
        self.in_rf_que_1_box.setObjectName("in_rf_que_1_box")
        self.in_rf_que_1 = QtWidgets.QComboBox(self.in_rf_que_1_box)
        self.in_rf_que_1.setGeometry(QtCore.QRect(4, 16, 241, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_rf_que_1.sizePolicy().hasHeightForWidth())
        self.in_rf_que_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        self.in_rf_que_1.setFont(font)
        self.in_rf_que_1.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_rf_que_1.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rf_que_1.setEditable(False)
        self.in_rf_que_1.setObjectName("in_rf_que_1")
        self.in_rf_que_1.addItem("")
        self.in_rf_que_1.setItemText(0, "")
        self.in_rf_que_1.addItem("")
        self.in_rf_que_1.addItem("")
        self.in_rf_que_1.addItem("")
        self.in_rf_que_1.addItem("")
        self.in_rf_que_1.addItem("")
        self.in_categories.addTab(self.rf_in, "РФ-2013")
        self.rk_in = QtWidgets.QWidget()
        self.rk_in.setStyleSheet("")
        self.rk_in.setObjectName("rk_in")
        self.frame_2 = QtWidgets.QFrame(self.rk_in)
        self.frame_2.setGeometry(QtCore.QRect(0, 4, 412, 364))
        self.frame_2.setStyleSheet("Background-color: #ffffff;\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 80, 69, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.in_rk_e = QtWidgets.QComboBox(self.groupBox_4)
        self.in_rk_e.setEnabled(True)
        self.in_rk_e.setGeometry(QtCore.QRect(4, 12, 61, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.in_rk_e.setFont(font)
        self.in_rk_e.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down {width:1}\n"
"")
        self.in_rk_e.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rk_e.setEditable(False)
        self.in_rk_e.setIconSize(QtCore.QSize(16, 16))
        self.in_rk_e.setFrame(True)
        self.in_rk_e.setObjectName("in_rk_e")
        self.in_rk_e.addItem("")
        self.in_rk_e.setItemText(0, "")
        self.in_rk_e.addItem("")
        self.in_rk_e.addItem("")
        self.in_rk_e.addItem("")
        self.in_rk_e.addItem("")
        self.in_rk_e.addItem("")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setGeometry(QtCore.QRect(172, 80, 69, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.in_rk_f = QtWidgets.QComboBox(self.groupBox_5)
        self.in_rk_f.setEnabled(True)
        self.in_rk_f.setGeometry(QtCore.QRect(4, 12, 61, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.in_rk_f.setFont(font)
        self.in_rk_f.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down {width:1}\n"
"")
        self.in_rk_f.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rk_f.setEditable(False)
        self.in_rk_f.setIconSize(QtCore.QSize(16, 16))
        self.in_rk_f.setFrame(True)
        self.in_rk_f.setObjectName("in_rk_f")
        self.in_rk_f.addItem("")
        self.in_rk_f.setItemText(0, "")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.in_rk_f.addItem("")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_6.setGeometry(QtCore.QRect(302, 80, 69, 45))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.groupBox_6.setObjectName("groupBox_6")
        self.in_rk_g = QtWidgets.QComboBox(self.groupBox_6)
        self.in_rk_g.setEnabled(True)
        self.in_rk_g.setGeometry(QtCore.QRect(4, 12, 61, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.in_rk_g.setFont(font)
        self.in_rk_g.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down {width:1}\n"
"")
        self.in_rk_g.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rk_g.setEditable(False)
        self.in_rk_g.setIconSize(QtCore.QSize(16, 16))
        self.in_rk_g.setFrame(True)
        self.in_rk_g.setObjectName("in_rk_g")
        self.in_rk_g.addItem("")
        self.in_rk_g.setItemText(0, "")
        self.in_rk_g.addItem("")
        self.in_rk_g.addItem("")
        self.in_rk_g.addItem("")
        self.in_rk_que_1_box = QtWidgets.QGroupBox(self.frame_2)
        self.in_rk_que_1_box.setGeometry(QtCore.QRect(82, 192, 249, 57))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_rk_que_1_box.sizePolicy().hasHeightForWidth())
        self.in_rk_que_1_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.in_rk_que_1_box.setFont(font)
        self.in_rk_que_1_box.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.in_rk_que_1_box.setObjectName("in_rk_que_1_box")
        self.in_rk_que_1 = QtWidgets.QComboBox(self.in_rk_que_1_box)
        self.in_rk_que_1.setGeometry(QtCore.QRect(4, 20, 241, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_rk_que_1.sizePolicy().hasHeightForWidth())
        self.in_rk_que_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        self.in_rk_que_1.setFont(font)
        self.in_rk_que_1.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_rk_que_1.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rk_que_1.setEditable(False)
        self.in_rk_que_1.setObjectName("in_rk_que_1")
        self.in_rk_que_1.addItem("")
        self.in_rk_que_1.setItemText(0, "")
        self.in_rk_que_1.addItem("")
        self.in_rk_que_1.addItem("")
        self.in_rk_que_1.addItem("")
        self.in_rk_que_2_box = QtWidgets.QGroupBox(self.frame_2)
        self.in_rk_que_2_box.setGeometry(QtCore.QRect(82, 192, 249, 57))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_rk_que_2_box.sizePolicy().hasHeightForWidth())
        self.in_rk_que_2_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.in_rk_que_2_box.setFont(font)
        self.in_rk_que_2_box.setStyleSheet("QGroupBox {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* position at the top center */\n"
"    padding: 0 3px;\n"
"}")
        self.in_rk_que_2_box.setObjectName("in_rk_que_2_box")
        self.in_rk_que_2 = QtWidgets.QComboBox(self.in_rk_que_2_box)
        self.in_rk_que_2.setGeometry(QtCore.QRect(4, 20, 241, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_rk_que_2.sizePolicy().hasHeightForWidth())
        self.in_rk_que_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        self.in_rk_que_2.setFont(font)
        self.in_rk_que_2.setStyleSheet("QComboBox {\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-width:0;\n"
"}")
        self.in_rk_que_2.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.in_rk_que_2.setEditable(False)
        self.in_rk_que_2.setObjectName("in_rk_que_2")
        self.in_rk_que_2.addItem("")
        self.in_rk_que_2.setItemText(0, "")
        self.in_rk_que_2.addItem("")
        self.in_rk_que_2.addItem("")
        self.in_rk_que_2.addItem("")
        self.in_rk_que_2.addItem("")
        self.in_categories.addTab(self.rk_in, "")
        self.out_categories = QtWidgets.QTabWidget(self.centralwidget)
        self.out_categories.setGeometry(QtCore.QRect(472, 32, 412, 412))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_categories.sizePolicy().hasHeightForWidth())
        self.out_categories.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        self.out_categories.setFont(font)
        self.out_categories.setAutoFillBackground(False)
        self.out_categories.setStyleSheet("QTabBar::tab {\n"
"    padding-top: 4px;\n"
"    padding-bottom: 4px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    width: 136;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    border-top: 2px solid #C2C7CB;\n"
"    alignment: center;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: #F0F1EB\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"  \n"
"    background: #ffffff;\n"
"}\n"
"QTabWidget::pane{}\n"
"QTabBar::tab.rf2013{\n"
"    border-top-left-radius: 30px;\n"
"}\n"
"QTabWidget::tab-bar{\n"
"border-top-left-radius: 30px;\n"
"}")
        self.out_categories.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.out_categories.setObjectName("out_categories")
        self.rf_out = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.rf_out.setFont(font)
        self.rf_out.setStyleSheet("QTabWidget::pane {}")
        self.rf_out.setObjectName("rf_out")
        self.frame_4 = QtWidgets.QFrame(self.rf_out)
        self.frame_4.setGeometry(QtCore.QRect(0, 4, 412, 364))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("Background-color: #ffffff;\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(16, 96, 381, 129))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLayoutWidget_2.sizePolicy().hasHeightForWidth())
        self.verticalLayoutWidget_2.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.out_rf_category = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_rf_category.sizePolicy().hasHeightForWidth())
        self.out_rf_category.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rf_category.setFont(font)
        self.out_rf_category.setText("")
        self.out_rf_category.setObjectName("out_rf_category")
        self.horizontalLayout_10.addWidget(self.out_rf_category)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.out_rf_profit = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_rf_profit.sizePolicy().hasHeightForWidth())
        self.out_rf_profit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rf_profit.setFont(font)
        self.out_rf_profit.setText("")
        self.out_rf_profit.setObjectName("out_rf_profit")
        self.horizontalLayout_9.addWidget(self.out_rf_profit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.out_categories.addTab(self.rf_out, "РФ-2013")
        self.rk_out = QtWidgets.QWidget()
        self.rk_out.setStyleSheet("")
        self.rk_out.setObjectName("rk_out")
        self.frame_5 = QtWidgets.QFrame(self.rk_out)
        self.frame_5.setGeometry(QtCore.QRect(0, 4, 412, 364))
        self.frame_5.setStyleSheet("Background-color: #ffffff;\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(28, 16, 357, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.out_rk_superclass = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_superclass.setFont(font)
        self.out_rk_superclass.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.out_rk_superclass.setText("")
        self.out_rk_superclass.setAlignment(QtCore.Qt.AlignCenter)
        self.out_rk_superclass.setObjectName("out_rk_superclass")
        self.horizontalLayout_3.addWidget(self.out_rk_superclass)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.out_rk_class = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_class.setFont(font)
        self.out_rk_class.setText("")
        self.out_rk_class.setAlignment(QtCore.Qt.AlignCenter)
        self.out_rk_class.setObjectName("out_rk_class")
        self.horizontalLayout_6.addWidget(self.out_rk_class)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.out_rk_subclass = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_subclass.setFont(font)
        self.out_rk_subclass.setText("")
        self.out_rk_subclass.setAlignment(QtCore.Qt.AlignCenter)
        self.out_rk_subclass.setObjectName("out_rk_subclass")
        self.horizontalLayout_7.addWidget(self.out_rk_subclass)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setStyleSheet("background-color: #F0F1EB;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.out_rk_e_num = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_e_num.setFont(font)
        self.out_rk_e_num.setText("")
        self.out_rk_e_num.setAlignment(QtCore.Qt.AlignCenter)
        self.out_rk_e_num.setObjectName("out_rk_e_num")
        self.horizontalLayout_8.addWidget(self.out_rk_e_num)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.out_rk_f_num = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_f_num.setFont(font)
        self.out_rk_f_num.setText("")
        self.out_rk_f_num.setAlignment(QtCore.Qt.AlignCenter)
        self.out_rk_f_num.setObjectName("out_rk_f_num")
        self.horizontalLayout_4.addWidget(self.out_rk_f_num)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.out_rk_g_num = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_rk_g_num.setFont(font)
        self.out_rk_g_num.setText("")
        self.out_rk_g_num.setAlignment(QtCore.Qt.AlignCenter)
        self.out_rk_g_num.setObjectName("out_rk_g_num")
        self.horizontalLayout_5.addWidget(self.out_rk_g_num)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.out_categories.addTab(self.rk_out, "")
        self.prms_out = QtWidgets.QWidget()
        self.prms_out.setObjectName("prms_out")
        self.frame_6 = QtWidgets.QFrame(self.prms_out)
        self.frame_6.setGeometry(QtCore.QRect(0, 4, 412, 364))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("Background-color: #ffffff;\n"
"border-bottom-right-radius: 30px;\n"
"border-bottom-left-radius: 30px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_6)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(24, 72, 365, 189))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.out_prms_superclass = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_prms_superclass.setFont(font)
        self.out_prms_superclass.setText("")
        self.out_prms_superclass.setObjectName("out_prms_superclass")
        self.horizontalLayout_11.addWidget(self.out_prms_superclass)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_12.addWidget(self.label_23)
        self.out_prms_class = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_prms_class.setFont(font)
        self.out_prms_class.setText("")
        self.out_prms_class.setObjectName("out_prms_class")
        self.horizontalLayout_12.addWidget(self.out_prms_class)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_13.addWidget(self.label_25)
        self.out_prms_subclass = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.out_prms_subclass.setFont(font)
        self.out_prms_subclass.setText("")
        self.out_prms_subclass.setObjectName("out_prms_subclass")
        self.horizontalLayout_13.addWidget(self.out_prms_subclass)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.out_categories.addTab(self.prms_out, "")
        self.info_button = QtWidgets.QPushButton(self.centralwidget)
        self.info_button.setGeometry(QtCore.QRect(0, 0, 57, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        self.info_button.setFont(font)
        self.info_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_button.setStyleSheet("QPushButton:hovered{\n"
"    background-color: red;\n"
"}\n"
"QPushButton#evilButton:pressed {\n"
"    background-color: rgb(224, 0, 0);\n"
"    border-style: inset;\n"
"}")
        self.info_button.setAutoDefault(False)
        self.info_button.setFlat(True)
        self.info_button.setObjectName("info_button")
        self.info_panel = QtWidgets.QFrame(self.centralwidget)
        self.info_panel.setGeometry(QtCore.QRect(0, 0, 905, 465))
        self.info_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_panel.setObjectName("info_panel")
        self.textBrowser = QtWidgets.QTextBrowser(self.info_panel)
        self.textBrowser.setGeometry(QtCore.QRect(172, 24, 557, 361))
        self.textBrowser.setStyleSheet("border-width:0")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.info_panel)
        self.pushButton.setGeometry(QtCore.QRect(408, 408, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-width:4")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.in_categories.setCurrentIndex(0)
        self.in_rf_stars.setCurrentIndex(0)
        self.out_categories.setCurrentIndex(1)
        self.out_categories.currentChanged['int'].connect(self.out_rf_category.clear) # type: ignore
        self.out_categories.currentChanged['int'].connect(self.out_rf_profit.clear) # type: ignore
        self.out_categories.currentChanged['int'].connect(self.out_rk_superclass.clear) # type: ignore
        self.out_categories.currentChanged['int'].connect(self.out_rk_class.clear) # type: ignore
        self.out_categories.currentChanged['int'].connect(self.out_rk_subclass.clear) # type: ignore
        self.out_categories.currentChanged['int'].connect(self.out_rk_g_num.clear) # type: ignore
        self.out_categories.currentChanged['int'].connect(self.out_rk_e_num.clear) # type: ignore
        self.out_categories.currentChanged['int'].connect(self.out_rk_f_num.clear) # type: ignore
        self.out_categories.currentChanged['int'].connect(self.out_prms_superclass.clear) # type: ignore
        self.out_categories.currentChanged['int'].connect(self.out_prms_class.clear) # type: ignore
        self.out_categories.currentChanged['int'].connect(self.out_prms_subclass.clear) # type: ignore
        self.pushButton.clicked.connect(self.info_panel.close) # type: ignore
        self.info_button.clicked.connect(self.info_panel.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "/"))
        self.in_rf_category.setItemText(1, _translate("MainWindow", "A"))
        self.in_rf_category.setItemText(2, _translate("MainWindow", "B1"))
        self.in_rf_category.setItemText(3, _translate("MainWindow", "B2"))
        self.in_rf_category.setItemText(4, _translate("MainWindow", "C1"))
        self.in_rf_category.setItemText(5, _translate("MainWindow", "C2"))
        self.in_rf_category.setItemText(6, _translate("MainWindow", "D0"))
        self.in_rf_category.setItemText(7, _translate("MainWindow", "Dл"))
        self.in_rf_category.setItemText(8, _translate("MainWindow", "D1"))
        self.in_rf_category.setItemText(9, _translate("MainWindow", "D2"))
        self.in_rf_stars.setTabText(self.in_rf_stars.indexOf(self.in_rf_stars_nonetab), _translate("MainWindow", "none"))
        self.in_rf_stars.setTabText(self.in_rf_stars.indexOf(self.in_rf_stars_onetab), _translate("MainWindow", "*"))
        self.in_rf_stars.setTabText(self.in_rf_stars.indexOf(self.in_rf_stars_twotab), _translate("MainWindow", "**"))
        self.in_rf_que_2_box.setTitle(_translate("MainWindow", "Стадия освоения"))
        self.in_rf_que_2.setItemText(1, _translate("MainWindow", "Проект на утверждении"))
        self.in_rf_que_2.setItemText(2, _translate("MainWindow", "Проектирование ведётся"))
        self.in_rf_que_2.setItemText(3, _translate("MainWindow", "Проектирование задержано"))
        self.in_rf_que_2.setItemText(4, _translate("MainWindow", "Проектирование не планируется"))
        self.in_rf_que_1_box.setTitle(_translate("MainWindow", "Экономическая рентабельность"))
        self.in_rf_que_1.setItemText(1, _translate("MainWindow", "Рентабельны"))
        self.in_rf_que_1.setItemText(2, _translate("MainWindow", "Рентабельны в перспективе"))
        self.in_rf_que_1.setItemText(3, _translate("MainWindow", "Рентабельность не известна"))
        self.in_rf_que_1.setItemText(4, _translate("MainWindow", "Не рентабельны"))
        self.in_rf_que_1.setItemText(5, _translate("MainWindow", "Добываются в убыток"))
        self.groupBox_4.setTitle(_translate("MainWindow", "E"))
        self.in_rk_e.setItemText(1, _translate("MainWindow", "1.1"))
        self.in_rk_e.setItemText(2, _translate("MainWindow", "1.2"))
        self.in_rk_e.setItemText(3, _translate("MainWindow", "2"))
        self.in_rk_e.setItemText(4, _translate("MainWindow", "3.2"))
        self.in_rk_e.setItemText(5, _translate("MainWindow", "3.3"))
        self.groupBox_5.setTitle(_translate("MainWindow", "F"))
        self.in_rk_f.setItemText(1, _translate("MainWindow", "1.1"))
        self.in_rk_f.setItemText(2, _translate("MainWindow", "1.2"))
        self.in_rk_f.setItemText(3, _translate("MainWindow", "1.3"))
        self.in_rk_f.setItemText(4, _translate("MainWindow", "2.1"))
        self.in_rk_f.setItemText(5, _translate("MainWindow", "2.2"))
        self.in_rk_f.setItemText(6, _translate("MainWindow", "2.3"))
        self.in_rk_f.setItemText(7, _translate("MainWindow", "3.1"))
        self.in_rk_f.setItemText(8, _translate("MainWindow", "3.2"))
        self.in_rk_f.setItemText(9, _translate("MainWindow", "3.3"))
        self.in_rk_f.setItemText(10, _translate("MainWindow", "4"))
        self.groupBox_6.setTitle(_translate("MainWindow", "G"))
        self.in_rk_g.setItemText(1, _translate("MainWindow", "1"))
        self.in_rk_g.setItemText(2, _translate("MainWindow", "2+3"))
        self.in_rk_g.setItemText(3, _translate("MainWindow", "4"))
        self.in_rk_que_1_box.setTitle(_translate("MainWindow", "Определение"))
        self.in_rk_que_1.setItemText(1, _translate("MainWindow", "Эксплуатируются"))
        self.in_rk_que_1.setItemText(2, _translate("MainWindow", "Разрабатываются"))
        self.in_rk_que_1.setItemText(3, _translate("MainWindow", "Только разведаны"))
        self.in_rk_que_2_box.setTitle(_translate("MainWindow", "Определение"))
        self.in_rk_que_2.setItemText(1, _translate("MainWindow", "Частично изучены"))
        self.in_rk_que_2.setItemText(2, _translate("MainWindow", "Только локализованы"))
        self.in_rk_que_2.setItemText(3, _translate("MainWindow", "Плей нефтеносного района"))
        self.in_rk_que_2.setItemText(4, _translate("MainWindow", "Плей неизученного района"))
        self.in_categories.setTabText(self.in_categories.indexOf(self.rk_in), _translate("MainWindow", "РКООН"))
        self.label_18.setText(_translate("MainWindow", "Категория:"))
        self.label_17.setText(_translate("MainWindow", "Рентабельность:"))
        self.label.setText(_translate("MainWindow", "Надкласс"))
        self.label_8.setText(_translate("MainWindow", "Класс"))
        self.label_3.setText(_translate("MainWindow", "Подкласс"))
        self.label_5.setText(_translate("MainWindow", "Ось E"))
        self.label_4.setText(_translate("MainWindow", "Ось F"))
        self.label_6.setText(_translate("MainWindow", "Ось G"))
        self.out_categories.setTabText(self.out_categories.indexOf(self.rk_out), _translate("MainWindow", "РКООН"))
        self.label_21.setText(_translate("MainWindow", "Надкласс:"))
        self.label_23.setText(_translate("MainWindow", "Класс:"))
        self.label_25.setText(_translate("MainWindow", "Подкласс:"))
        self.out_categories.setTabText(self.out_categories.indexOf(self.prms_out), _translate("MainWindow", "PRMS"))
        self.info_button.setText(_translate("MainWindow", "INFO"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Вы можете переводить категории и соответствующие им количества нефти РКООН в РФ-2013. Для этого следуйте инструкциям: </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1. Введите категорию путём выбора осей EFG </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2. Если программа предложила выбрать уточнение выберете из списка наиболее близко описывающее данные объёмы углеводородов. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">3. Укажите количество углеводородов без указания единиц измерения. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">4. Если вы хотите ввести ещё категорию то вы можете это сделать в нижеследующем окошке. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Примечание:</span><span style=\" font-size:12pt;\"> Если программа выдаёт ошибку «нестандартная категория», то вы ввели комбинацию EFG, которая является нестандартной и не переводится согласно связующему документу ООН, или вы ввели уточнение, которое не может соотноситься с данной категорией. На данный момент программа находится в стадии разработки о всех ошибках сообщайте на почту официальную почту разработчиков artem.vasin.55@inbox.ru.</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
